### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to a member function toNode

### ISSUE THREAD

**Issue by remotehelp** [ezyang/htmlpurifier#115]
I use PHP 7.1 and latest HTML Purifier 4.8.0 (.zip) with this code:
```
<?php

require_once 'lib/htmlpurifier/library/HTMLPurifier.auto.php';

$config = HTMLPurifier_Config::createDefault();
$config->set('HTML.Allowed', 'a[href|rel|target|title], abbr, acronym, b, blockquote, caption, cite, code, dd, del, dfn, div, dl, dt, em, i, img[src|width|height|alt|title], ins, kbd, li, ol, p, pre, s, strike, strong, sub, sup, table, tbody, td, tfoot, th, thead, tr, tt, u, ul, var, iframe[src|width|height|frameborder|allowfullscreen]');
$config->set('HTML.SafeIframe', true);
$config->set('URI.SafeIframeRegexp', '%^(http(s)?:)?//(www.youtube.com/embed/|player.vimeo.com/video/)%');

// **'AutoFormat.RemoveEmpty' cause Fatal error in PHP 7.1**
$config->set('AutoFormat.RemoveEmpty', true);
$config->set('HTML.Nofollow', true);
$config->set('HTML.TargetBlank', true);
$purifier = new HTMLPurifier($config);


$dirty_html = '<div class="bdaia-post-content">
							<div id="dfp-single" class="right"><div class="dfp-wrapper">
								<div id="div-gpt-ad-1477334279140-0"><script>googletag.cmd.push(function(){googletag.display(\'div-gpt-ad-1477334279140-0\');});</script></div>
							</div></div>
	<p>Немецкий исследователь Флориан Ойхнер (Florian Euchner) aka Jeija <a href="https://github.com/Jeija/bluefluff">выложил на GitHub</a> очень занимательный репозиторий, в котором представлены результаты его исследований интерактивной игрушки Furby Connect. Как не сложно понять из названия, разработчики Hasbro создали «умную» игрушку, которая способна сообщаться с официальными Android и iOS приложениями Furby Connect World посредством Bluetooth. «Усовершенствованный чип интеллекта позволяет Furby Connect учиться и расширять словарный запас. А увеличенная в 16 раз память может хранить более 1000 фраз», — гласит официальное описание игрушки.</p>
<p>На GitHub Jeija пишет, что в ходе его исследований ни один Furby не пострадал (ломать дорогую игрушку физически не понадобилось), но исследователю удалось выяснить, что игрушка содержит два микроконтроллера. Микроконтроллер GeneralPlus отвечает за движения, речь и LCD-глаза игрушечного зверька, а второй микроконтроллер от Nordic Semiconductor контролирует все, что связано с Bluetooth Low Energy. Более точные характеристики Ойхнеру неизвестны, так как ради них пришлось бы «вскрыть» Furby, но исследователь предполагает, что игрушка использует процессор серии GPL16XXXX.</p>
<div class="bdaia-p-inline-e3-desktop"><div class="bdaia-e3-container"></div></div>
<blockquote><p>«С Furby можно взаимодействовать как автономно, так и подключив [игрушку] к Android / iOS приложению Furby Connect World, которое полностью контролирует движения и речь, а также передает обновления, полученные с серверов Hasbro на Amazon AWS», — объясняет Ойхнер.</p></blockquote>
<p>На GitHub исследователь тщательно задокументировал, как работают «мозги» Furby, разобрав, как работает Furby Bluetooth, механизм обновлений через приложение, доступные игрушке последовательности действий и так далее. Как уже можно было понять, исследователь сумел добраться до диагностического меню игрушки. Именно оно так жутко отображается в глазах Furby на приведенном ниже видео.</p>
<p><iframe src="https://www.youtube.com/embed/FkblA_CxHgU" width="796" height="448" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p>Кстати, если исследование Ойхнера верно, то официальное приложение не утруждается использованием HTTPS:</p>
<blockquote><p>«При запуске Furby Connect World соединяется с сервером http://fluff-gameupdates.s3.amazonaws.com/ и загружает внутриигровой контент, к примеру, 3D-модели, фоновую музыку и другие звуки».</p></blockquote>
<p>Эта особенность уже привлекла внимание других исследователей. Так, бывший член группы LulzSec Джейк Дэвис (Jake Davis), также известный как Topiary, пишет у себя в Twitter, что игрушки, скорее всего, можно взломать, используя подходящую прокси. Тогда Furby можно будет передать «обновление», которое, например, заставит глаза зверька мигать красным светом и исполнять «Never Gonna Give You Up». Дэвис пишет, что многие читатели спросили его, что плохого во взломе Furby. В ответ хакер предложил зайти в магазин с тестовыми образцами Furby, распространить вредоносный файл и наслаждаться эффектом.</p>
<blockquote class="twitter-tweet" data-width="550">
<p lang="en" dir="ltr">A Furby that can be updated from "the app" is a Furby whose eyes will flash red and whose mouth will constantly sing Never Gonna Give You Up</p>
<p>— Jake Davis (@DoubleJake) <a href="https://twitter.com/DoubleJake/status/823523614964256768">January 23, 2017</a></p>
</blockquote>
<p><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<p>Кроме того, Ойхнер создал кастомные DLC, которые позволяют загрузить в память Furby произвольные звуки. Так, на видео Ойхнер демонстрирует рикролл в исполнении Furby, заставляет игрушку цитировать Дональда Трампа, «Звездные войны» и так далее. Так как передавать Furby команды через приложение не слишком удобно, исследователь написал для этого программу <a href="https://github.com/Jeija/bluefluff">fluffd</a>, которая тоже опубликована на GitHub.</p>
<p><img class="aligncenter size-full wp-image-112984" src="https://xakep.ru/wp-content/uploads/2017/01/112983/Capture.png" alt="" width="931" height="406" srcset="https://xakep.ru/wp-content/uploads/2017/01/112983/Capture.png 931w, https://xakep.ru/wp-content/uploads/2017/01/112983/Capture-130x57.png 130w, https://xakep.ru/wp-content/uploads/2017/01/112983/Capture-400x174.png 400w, https://xakep.ru/wp-content/uploads/2017/01/112983/Capture-768x335.png 768w, https://xakep.ru/wp-content/uploads/2017/01/112983/Capture-610x266.png 610w, https://xakep.ru/wp-content/uploads/2017/01/112983/Capture-850x371.png 850w" sizes="(max-width: 931px) 100vw, 931px"></p>
<p>Между тем, Джейк Дэвис шутит в Twitter, что разработчикам Furby явно не стоит оснащать следующее поколение игрушек Wi-Fi, потому что тогда мы в одном шаге от Furby-ботнетов.</p>
<blockquote class="twitter-tweet" data-width="550">
<p lang="en" dir="ltr">Please, makers of Furby, do not enable WiFi in your next model. <a href="https://twitter.com/Hasbro">@Hasbro</a></p>
<p>— Jake Davis (@DoubleJake) <a href="https://twitter.com/DoubleJake/status/823525475242876928">January 23, 2017</a></p>
</blockquote>


<p><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<span class="et_bloom_bottom_trigger"></span>						</div>';

$clean_html = $purifier->purify($dirty_html);

echo $clean_html;
```
When I set this "**$config->set('AutoFormat.RemoveEmpty', true);**" in php-error.log I get this:
```
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to assign property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 567
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to modify property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 568
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to assign property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 567
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to modify property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 568
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to assign property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 567
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to modify property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 568
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to assign property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 567
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to modify property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/MakeWellFormed.php on line 568
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to assign property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Arborize.php on line 17
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Warning:  Attempt to assign property of non-object in /var/www/lib/htmlpurifier/library/HTMLPurifier/Arborize.php on line 18
[28-Jan-2017 05:17:02 Europe/Kiev] PHP Fatal error:  Uncaught Error: Call to a member function toNode() on array in /var/www/lib/htmlpurifier/library/HTMLPurifier/Arborize.php:29
Stack trace:
#0 /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/FixNesting.php(49): HTMLPurifier_Arborize::arborize(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#1 /var/www/lib/htmlpurifier/library/HTMLPurifier/Strategy/Composite.php(24): HTMLPurifier_Strategy_FixNesting->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /var/www/lib/htmlpurifier/library/HTMLPurifier.php(211): HTMLPurifier_Strategy_Composite->execute(Array, Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#3 /var/www/purifier.php(62): HTMLPurifier->purify('<div class="bda...')
#4 {main}
  thrown in /var/www/lib/htmlpurifier/library/HTMLPurifier/Arborize.php on line 29
```
This Fatal error happens if **opcache.enable=1**
```
[opcache]
; Determines if Zend OPCache is enabled
opcache.enable=1
```
Disabling opcache (_opcache.enable=0_) this is not permanent solution and this bug must be debugged!

**Comment by irfanevrens** [comment]
There is a RECURSION problem on $tokens variable in FixNesting Strategy.

**Comment by irfanevrens** [comment]
$tokens contains empty arrays and it should contains HTMLPurifier_Token[]

**Comment by ezyang** [comment]
I think it's this one: https://github.com/ezyang/htmlpurifier/issues/108

Root cause is an Opcode cache miscompilation. If you upgrade PHP that should also fix the problem; although we have a patch to fix at least some of the problems.

**Comment by irfanevrens** [comment]
Is there any roadmap for 4.8.1 or 4.9.0?

**Comment by ezyang** [comment]
After I clear out the issue and patch queue :)
